name: Coding Standards

on:
  push:
  pull_request:

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:2.1
          coverage: none

      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 2
          max_attempts: 2
          command: composer update --no-interaction --no-progress

      - name: Execute PHPCS
        run: vendor/bin/phpcs -s
